[tool.setuptools_scm]
write_to = "src/kirameki/_version.py"
version_scheme = "python-simplified-semver"
local_scheme = "no-local-version"

[build-system]
requires = ["setuptools >= 41.0", "wheel", "setuptools_scm[toml] >= 3.4"]
build-backend = "setuptools.build_meta"
